version: '2.10'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./database:/var/lib/mysql

  application:
    container_name: application
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/blog/app
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/blog/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application
      - database